#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "journiv"
name = "Journiv"
description.en = "Self hosted private journaling"
description.fr = "Journal intime privé auto-hébergé"

version = "0.1.0-19~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "PolyForm-Noncommercial-1.0.0"
website = "https://www.journiv.com/"
admindoc = "https://www.journiv.com/docs/installation"
code = "https://github.com/journiv/journiv-app"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/journiv/journiv-app/archive/refs/tags/v0.1.0-beta.19.tar.gz"
    sha256 = "38d1557e1203131a818e52d1b9bfc89b84711d3b75093e157979d34aca260335"
    
    # beta tags are filtered anyway
    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3-dev, python3-venv, python3, redis-server"

	[resources.apt.extras.mise]
	repo = "deb https://mise.jdx.dev/deb stable main"
	key = "https://mise.jdx.dev/gpg-key.pub"
	packages = [
		"mise"
	]

    [resources.database]
    type = "postgresql"
