#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

random_key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=random_key --value=$random_key

redis_db=$(ynh_redis_get_free_db)
celery_db=$(ynh_redis_get_free_db)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Self hosted private journaling" --log="/var/log/$app/$app.log"

# Celery
    ynh_config_add_systemd --service="$app-celery" --template="celery.service"
    ynh_config_add_systemd --service="$app-celery-beat" --template="celery-beat.service"

    yunohost service add "$app-celery" --description="Celery for $app" --log="/var/log/$app/celery-worker.log"
    yunohost service add "$app-celery-beat" --description="Celery beat for $app" --log="/var/log/$app/celery-beat.log"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd $install_dir
    python3 -m venv $install_dir/venv
    echo "source $install_dir/venv/bin/activate" >> $install_dir/.bashrc
    source $install_dir/venv/bin/activate
    ynh_hide_warnings $install_dir/venv/bin/pip install -r requirements/prod.txt
    ynh_hide_warnings alembic upgrade head
    deactivate
popd

chmod -R 775 "$install_dir"
chmod o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

mkdir -p "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start"

# Celery
    ynh_systemctl --service="$app-celery" --action="start"
    ynh_systemctl --service="$app-celery-beat" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
