#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
yunohost service remove "$app"
yunohost service remove "$app-celery"
yunohost service remove "$app-celery-beat"

ynh_config_remove_systemd "$app"
ynh_config_remove_systemd "$app-celery"
ynh_config_remove_systemd "$app-celery-beat"

ynh_redis_remove_db "$redis_db"
ynh_redis_remove_db "$celery_db"

ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
