#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env venv"

pushd $install_dir
    source $install_dir/venv/bin/activate
    ynh_hide_warnings $install_dir/venv/bin/pip install -r requirements/prod.txt
    ynh_hide_warnings alembic upgrade head
    deactivate
popd

chmod -R 775 "$install_dir"
chmod o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
#ynh_script_progression "Updating $app's configuration files..."

#ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Self hosted private journaling" --log="/var/log/$app/$app.log"

# Celery
    ynh_config_add_systemd --service="$app-celery" --template="celery.service"
    ynh_config_add_systemd --service="$app-celery-beat" --template="celery-beat.service"

    yunohost service add "$app-celery" --description="Celery for $app" --log="/var/log/$app/celery-worker.log"
    yunohost service add "$app-celery-beat" --description="Celery beat for $app" --log="/var/log/$app/celery-beat.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

# Celery
    ynh_systemctl --service="$app-celery" --action="start"
    ynh_systemctl --service="$app-celery-beat" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
